domain: tomadimitrie.github.io
title: Blog
description: 
url: "https://tomadimitrie.github.io"
github_username:  tomadimitrie

theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-archives-v2

collections:
  ctfs:
    output: true

category-generator:
  collections:
    - ctfs

jekyll-archives:
  ctfs:
    enabled:
      - categories
    permalinks:
      categories: "/category/:name/"

