domain: tomadimitrie.github.io
title: Blog
description: 
url: "https://tomadimitrie.github.io"
github_username:  tomadimitrie

theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  ctfs:
    output: true

