source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "base64"
gem "csv"
gem "logger"

gem "minima"

group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-feed"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
